export const trending = (req,res) => res.send("Trending Videos")
export const see = (req,res) => res.send("See Videos")
export const edit = (req,res) => res.send("Edit Videos")
export const search = (req,res) => res.send("Search Videos")
export const upload = (req,res) => res.send("Upload Videos")
export const deleteVideo = (req,res) => res.send("Delete Videos")